// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Container.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$2 from "./sections/Header.tsx";
import * as $$$$$$3 from "./sections/IncidentPage.tsx";
import * as $$$$$$4 from "./sections/ItWorks.tsx";
import * as $$$$$$5 from "./sections/PastIncidents.tsx";
import * as $$$$$$6 from "./sections/RegisterToReportBugForm.tsx";
import * as $$$$$$7 from "./sections/RegisterToUpdatesForm.tsx";
import * as $$$$$$8 from "./sections/SecondSection.tsx";
import * as $$$$$$9 from "./sections/StatusDetails.tsx";
import * as $$$$$$10 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Container.tsx": $$$$$$0,
    "site/sections/Footer.tsx": $$$$$$1,
    "site/sections/Header.tsx": $$$$$$2,
    "site/sections/IncidentPage.tsx": $$$$$$3,
    "site/sections/ItWorks.tsx": $$$$$$4,
    "site/sections/PastIncidents.tsx": $$$$$$5,
    "site/sections/RegisterToReportBugForm.tsx": $$$$$$6,
    "site/sections/RegisterToUpdatesForm.tsx": $$$$$$7,
    "site/sections/SecondSection.tsx": $$$$$$8,
    "site/sections/StatusDetails.tsx": $$$$$$9,
    "site/sections/Theme/Theme.tsx": $$$$$$10,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
